### ISSUE TITLE
styled-component の処遇について

### ISSUE THREAD

**Issue by ten986** [yumemi-inc/yumeshop-frontend#214]
やや emotion に移行したい気持ちがある。どうするべきか考える

**Comment by kkeeth** [comment]
同意．CSS-in-JS やるなら `emotion` の方が軽いし良いかと．
ただ，zero-runtime CSS-in-JS も気になるところ

**Comment by kkeeth** [comment]
#211 と #227 も一緒に解決する可能性があるので，styled-components をやめたいかも

**Comment by kkeeth** [comment]
`emotion` への移行で決定．

zero-runtime CSS-in-JS は，やれることが減るのが懸念なので一旦なしで．
インターン生の反応次第で．
