### ISSUE TITLE
ディレクトリ構成についての検討

### ISSUE THREAD

**Issue by ten986** [yumemi-inc/yumeshop-frontend#216]
- atomic design やめたい
- テストは対象のファイルと同じディレクトリに置きたい
- `src/styles/Tokens.ts` のようなコンポーネント以外のファイルは小文字始まりで統一したい

**Comment by kkeeth** [comment]
* atomic design は壊す
* テストは対象のファイルと同じディレクトリに置きたい
  * これはやっちゃって
* src/styles/Tokens.ts のようなコンポーネント以外のファイルは小文字始まりで統一したい
  * これもやっちゃって

**Comment by kkeeth** [comment]
方針としては __関心ごとでまとまっていれば何でも良い__
ざっくり `atoms`, `organisms`をなくしてエイヤで親に入れても良い．

**Comment by ten986** [comment]
index.tsx にファイル置くのがちょっとイヤかも
index.tsは子ファイルのexportのみをすべきで、コンポーネントは例えばfooter.tsxみたいな命名にすべき

**Comment by kkeeth** [comment]
一旦やりたいことは一通りできたのでクローズ
