### ISSUE TITLE
storybook-addon-next を導入したいかも

### ISSUE THREAD

**Issue by ten986** [yumemi-inc/yumeshop-frontend#237]

**Comment by kkeeth** [comment]
入れちゃっても良いかも(=ﾟωﾟ)ﾉ

**Comment by kkeeth** [comment]
と思ったが，

> This addon has been deprecated in favor of [@storybook/nextjs](https://www.npmjs.com/package/@storybook/nextjs) which is the Storybook official addon for supporting Next.js features in Storybook.

と書いてあり，かつ `@storybook/nextjs` 入っているので入れたい理由が聞きたいかも(=ﾟωﾟ)ﾉ

https://www.npmjs.com/package/storybook-addon-next

**Comment by ten986** [comment]
なるほど、deprecated な上で `@storybook/nextjs` が入ってるなら問題なさそうですね。
いくつか next 特有な機能が storybook 上で動かなかった記憶がある、というモチベーションだったので、問題ないと思います

**Comment by ten986** [comment]
特に問題なさそうなので close しちゃいます
